//
// Created by jadel on 07/10/2026.
//

#ifndef ACTIVIDADCOLABORATIVA2_CALCULADORAAVANZADA_H
#define ACTIVIDADCOLABORATIVA2_CALCULADORAAVANZADA_H


class CalculadoraAvanzada {
};


#endif //ACTIVIDADCOLABORATIVA2_CALCULADORAAVANZADA_H
