//
// Created by jadel on 10/10/2026.
//

#ifndef ACTIVIDADCOLABORATIVA2_LISTAGENERICA_H
#define ACTIVIDADCOLABORATIVA2_LISTAGENERICA_H


class ListaGenerica {
};


#endif //ACTIVIDADCOLABORATIVA2_LISTAGENERICA_H
